language: python
matrix:
  include:
    - { python: "2.7" }
    - { python: "3.4" }
    - { python: "3.5" }
    - { python: "3.6" }
    - { python: "3.7", dist: xenial }  # Python 3.7+ requires Xenial
    - { python: "3.8-dev", dist: xenial }  # Python 3.8+ requires Xenial

install:
  - "pip install coverage"
  - "pip install nose"
  - "pip install --upgrade pip"
  - "pip install -e .[testing]"

  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls && export HAS_COVERALLS=1; fi

script: "nosetests -v --with-coverage --cover-package=tgext.mailer --cover-erase"

after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi
